export const chipsOptionList = [
  { value: "jelly" },
  { value: "sweet" },
  { value: "cake" },
  { value: "cute" },
  { value: "breve" },
  { value: "latte" },
  { value: "mocha" },
  { value: "pink" },
  { value: "apple" },
  { value: "banana" },
  { value: "kiwi" },
  { value: "purple" },
  { value: "green" },
];
